Capstone Project
hiwina/Capstone-Project-1 pull request #1
Opened 2022-12-02 08:51 UTC by hiwina

2022-12-02 12:21 UTC, uwadonat requested changes
## Hi @hiwina,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### Highlights
- Professional readme file ✔️
- Descriptive pull request message ✔️
- Good commit messages ✔️
![almoo](https://user-images.githubusercontent.com/65860678/205291691-0554fe23-394d-4586-a46e-5fe153c1c7db.gif)

## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @uwadonat in your question so I can receive the notification.

------
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-12-02 12:21 UTC, uwadonat commented on index.js
>  //     const info = document.createElement('div');
- [ ] Let's remove all commented lines to make our code more clean.

2022-12-02 12:21 UTC, uwadonat commented on README.md
> +
- [ ] This link should be your deployed application. now it is pointing to your github page. Kindly fix it.

2022-12-02 12:21 UTC, uwadonat commented on README.md
> +
- [ ] In your presentation, you should highlight a piece of project you find interesting or you are proud of making.

2022-12-03 01:38 UTC, mgmediaweb requested changes
Hi @hiwina , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

![almost5](https://user-images.githubusercontent.com/41912912/205416338-901a0ea8-8bcd-4b09-8898-4d1b99a45453.gif)

 ## Highlights 💯 
- Good job following the advice of the previous reviewer ✔️ 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-03 01:38 UTC, mgmediaweb commented on README.md
> +- [Live Demo Link](ttps://hiwina.github.io/Capstone-Project-1/)
Kindly, I suggest you follow the previous reviewer's advice, the LIVE DEMO link, currently connects to your repository, and it should point to the deployed version of your site.

2022-12-03 02:36 UTC, uwadonat approved these changes
## Hi @hiwina,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### Congratulations! 🎉 


![approval1](https://user-images.githubusercontent.com/65860678/205418417-0c7141b2-3c36-4b80-a8ea-6d15a10380ef.gif)
# Status: Approved ✔️✔️✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @uwadonat in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-12-03 02:37 UTC, merged